catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # read
    #1er paramètre : url, 2è : la vue, 3e (optionnel) : le nom de la route (qui pourra ensuite s'utiliser ainsi dans la vue : {% url 'index' %})
    path('', views.index, name='index'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>',
         views.AuthorDetailView.as_view(),
         name='author-detail'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('my-books/',
         views.LoanedBooksByUserListView.as_view(),
         name='my-borrowed'),
    # create
    path('user/create/', views.create_user, name='user-create'),
    path('author/create/', views.create_author, name='author-create'),
    path('book/create/', views.create_book, name='book-create'),
    path('book/<uuid:pk>/renew/', views.renew_book, name='book-renew'),
    path('book/<uuid:pk>/return/', views.return_book, name='book-return'),
    path('book_instance/create/',
         views.create_book_instance,
         name='book_instance-create'),
    path('genre/create/', views.create_genre, name='genre-create'),
    # update
    path('author/<int:pk>/update/',
         views.AuthorUpdate.as_view(),
         name='author-update'),
    path('book/<int:pk>/update/',
         views.BookUpdate.as_view(),
         name='book-update'),
     path('book_instance/<uuid:pk>/read/',
         views.BookInstanceRead.as_view(),
         name='book_instance-read'),
     path('book_instance/<uuid:pk>/read/bookmark/',
         views.bookmark, name='book_instance-bookmark'),
    path('book_instance/<int:pk>/update/',
         views.BookInstanceUpdate.as_view(),
         name='book_instance-update'),
    path('genre/<int:pk>/update/',
         views.GenreUpdate.as_view(),
         name='genre-update'),
    # delete
    path('author/<int:pk>/delete/',
         views.AuthorDelete.as_view(),
         name='author-delete'),
    path('book/<int:pk>/delete/',
         views.BookDelete.as_view(),
         name='book-delete'),
    path('book_instance/<int:pk>/delete/',
         views.BookInstanceDelete.as_view(),
         name='book_instance-delete'),
    path('genre/<int:pk>/delete/',
         views.GenreDelete.as_view(),
         name='genre-delete'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Tout ce qui suit "catalog/" sera traité par le fichier "urls.py" de l'application "catalog" grâce à l'include
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse  # Cette fonction est utilisée pour formater les URL
import uuid  # Ce module est nécessaire à la gestion des identifiants unique (RFC 4122) pour les copies des livres
from django.contrib.auth.models import User
from datetime import date


# Model Genre
class Permission(models.Model):
    """Cet objet représente les permissions."""
    class Meta:
        # Création d'une permission. Elle sera - après migration - assignable à un groupe d'utilisateurs et la logique se fera ensuite dans le template, dans l'objet "perms" (qui est envoyé par défaut au template) - "{% if perms.catalog.read_authors_and_books %}")
        permissions = (("read_authors_and_books",
                        "Accès au listing des auteurs et des livres."), )

    def __str__(self):
        """Cette fonction est obligatoirement requise par Django.
           Elle retourne une chaîne de caractère pour identifier l'instance de la classe d'objet. L'appel se fait avec la fonction str(monModel)"""
        return self.name


# Model Genre
class Genre(models.Model):
    name = models.CharField(
        max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name


# Model Book
class Book(models.Model):
    """Cet objet représente un livre (mais ne traite pas les copies présentes en rayon)."""
    title = models.CharField(max_length=200)

    #  Un livre a un seul auteur, mais un auteur a écrit plusieurs livres.
    author = models.ForeignKey('Author', on_delete=models.CASCADE, null=True)

    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField(
        'ISBN',
        max_length=13,
        help_text=
        '13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'
    )

    #  un livre peut avoir plusieurs genres littéraire et réciproquement.
    genre = models.ManyToManyField(Genre,
                                   help_text='Select a genre for this book')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


# Model BookInstance
class BookInstance(models.Model):
    """Cet objet permet de modéliser les copies d'un ouvrage (i.e. qui peut être emprunté)."""
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    imprint = models.CharField(max_length=200)
    pdf_file = models.FileField(upload_to='book_pdfs/', blank=True, null=True)
    borrower = models.ForeignKey(User,
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 blank=True)
    due_back = models.DateField(null=True, blank=True)
    due_back_extension = models.IntegerField(default=0)
    bookmark = models.IntegerField(default=1)


    LOAN_STATUS = (
        ('m', 'Problème sur document'),
        ('o', 'Emprunté'),
        ('a', 'Disponible'),
        ('r', 'Réservé'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    def __str__(self):
        return f'{self.id} ("{self.book.title}" - {self.book.author})'


# Model Auteur
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """Retourne le nom et prénom de l'auteur."""
        return f'{self.last_name}, {self.first_name}'

catalog/views.py
import os
from django.shortcuts import render, get_object_or_404
from catalog.models import Book, Author, BookInstance, Genre, User
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .forms import UserModelForm, AuthorModelForm, BookModelForm, GenreModelForm, BookInstanceModelForm, RenewBookForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
import datetime
from django.views.generic.edit import UpdateView, DeleteView
#from sendgrid import SendGridAPIClient
#from sendgrid.helpers.mail import Mail
from django.http import JsonResponse
import json
"""
def send_mail(from_email, to_emails, subject, html_content):
    ""
    Easy wrapper for sending a single message to a recipient list. All members
    of the recipient list will see the other recipients in the 'To' field.

    If auth_user is None, use the EMAIL_HOST_USER setting.
    If auth_password is None, use the EMAIL_HOST_PASSWORD setting.

    Note: The API for this method is frozen. New code wanting to extend the
    functionality should use the EmailMessage class directly.
    ""
    message = Mail(from_email=from_email,
                   to_emails=to_emails,
                   subject=subject,
                   html_content=html_content)
    try:
        sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
        response = sg.send(message)
        print(response.status_code)
        print(response.body)
        print(response.headers)
    except Exception as e:
        print(e.message)
"""


def index(request):
    """View function for home page of site."""

    if request.method == 'POST':
        books = []
        if request.POST.get('book') != '':
            query = Book.objects.filter(
                title__istartswith=request.POST.get('book')).values()[0:10]

            for book in query:
                author = Author.objects.filter(pk=book['author_id'])[0]
                book['author'] = str(author)
                books.append(book)

        return JsonResponse({'books': books})

    num_books = Book.objects.all().count()
    latest_books = BookInstance.objects.order_by('-id')[:5]
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(
        status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Va compter les visites pour CHAQUE utilisateur indépendamment les uns des autres. La variable num_visits regarde si la session a déjà une valeur et lui attribue le chiffre 0 si ce n'est pas déjà le cas.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'latest_books': latest_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # send_mail('sokhona.salaha@gmail.com', 'salsdu19@gmail.com', 'Sujet : Votre compte.', '<strong>Message : Compte créé</strong>')

    return render(request, 'index.html', context=context)


# CREATE
# Le paramètre indique le chemin sur lequel rediriger l'utilisateur s'il n'est pas connecté
@login_required(login_url='/accounts/login/')
@permission_required('catalog.can_add_user', raise_exception=True)
def create_user(request):

    form = UserModelForm()

    if request.method == 'POST':
        form = UserModelForm(request.POST)

        if form.is_valid():
            form.save()
            # send_mail('salsdu19@gmail.com', 'Sujet : Votre compte.', '<strong>Message : Compte créé</strong>')

            return HttpResponseRedirect(reverse('index'))

    # A créer plus tard
    return render(request, 'create_update_form.html', {'form': form})


@login_required(login_url='/accounts/login/')
@permission_required('catalog.can_add_author', raise_exception=True)
def create_author(request):

    form = AuthorModelForm()

    if request.method == 'POST':
        form = AuthorModelForm(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('index'))

    return render(request, 'create_update_form.html', {'form': form})


@login_required(login_url='/accounts/login/')
@permission_required('catalog.can_add_book', raise_exception=True)
def create_book(request):

    form = BookModelForm()

    if request.method == 'POST':
        form = BookModelForm(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('index'))

    return render(request, 'create_update_form.html', {'form': form})


@login_required(login_url='/accounts/login/')
@permission_required('catalog.can_add_book_instance', raise_exception=True)
def create_book_instance(request):

    form = BookInstanceModelForm()

    if request.method == 'POST':
        form = BookInstanceModelForm(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('index'))

    return render(request, 'create_update_form.html', {'form': form})


@login_required(login_url='/accounts/login/')
@permission_required('catalog.can_add_genre', raise_exception=True)
def create_genre(request):

    form = GenreModelForm()

    if request.method == 'POST':
        form = GenreModelForm(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('index'))

    return render(request, 'create_update_form.html', {'form': form})


# READ
# Les class sont également une façon de retourner des résultats dans un template.
class AuthorListView(generic.ListView):
    model = Author
    context_object_name = 'authors_list'  # your own name for the list as a template variable
    # queryset = Book.objects.filter(title__icontains='one')[:5] # Get and return 5 books containing the title one
    # Le signe "-" indique à Django de sortir les résultats par ordre descendant
    queryset = Author.objects.all().order_by('last_name')
    # Gère la logique de la pagination. L'affichage est quant à lui géré par le template associé (en l'occurence, le template "base_generic").
    paginate_by = 10
    template_name = 'authors/authors_list.html'


class BookListView(generic.ListView):
    model = Book
    context_object_name = 'books_list'
    queryset = Book.objects.all().order_by('-id')
    paginate_by = 10
    template_name = 'books/books_list.html'

    def post(self, request):
        books = []
        if request.POST.get('filter') == 'Titre':
            books_query = Book.objects.all().order_by('title').values()
        elif request.POST.get('filter') == 'Auteur':
            books_query = Book.objects.all().order_by('author').values()

        for book in books_query:
            author = Author.objects.filter(pk=book['author_id'])[0]
            book['author'] = str(author)
            books.append(book)

        return JsonResponse({'books': books})


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'books/book_detail.html'

    def post(self, request, pk):
        if request.POST.get('borrow_book'):
            borrow_book(self, request)
        elif request.POST.get('return_book'):
            return_book(self, request)

        # Redirige vers l'URL d'origine
        return HttpResponseRedirect(self.request.path_info)


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'authors/author_detail.html'


# Les Mixins sont une autre façon de bloquer une page aux utilisateurs selon conditions (ici, que l'utilisateur soit connecté). Ils sont à utiliser pour les views de type "class".
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    login_url = '/accounts/login/'
    model = BookInstance
    context_object_name = 'borrows_list'
    template_name = 'users/user_list_borrows.html'
    paginate_by = 10

    # Redéfinit la méthode get_queryset pour n'afficher que les livres empruntés par l'utilisateur connecté et dont la date de retour n'est pas dépassée.
    def get_queryset(self):
        books = BookInstance.objects.filter(borrower=self.request.user).filter(
            status__exact='o').order_by('due_back')
        
        for book in books:
            if book.due_back < datetime.date.today():
                book.borrower = None
                book.status = 'a'
                book.due_back = None
                book.due_back_extension = 0
                book.save()

        return books


# UPDATE
class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_change_author'
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    template_name = 'create_update_form.html'


class BookUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_change_book'
    model = Book
    fields = ['title', 'summary']
    template_name = 'create_update_form.html'


class BookInstanceRead(LoginRequiredMixin,generic.DetailView):
    login_url = '/accounts/login/'
    model = BookInstance
    context_object_name = 'book_instance'
    template_name = 'books_instances/book_instance_read.html'
    fields = ['title', 'pdf_file']
    

@login_required(login_url='/accounts/login/')
def bookmark(request, pk):
    data = json.loads(request.body)

    if not data.get('current_page') or pk is None:
        return JsonResponse({'error': 'Il manque des données obligatoires.'}, status=400)

    try:
        book_instance = get_object_or_404(BookInstance, pk=pk)
        book_instance.bookmark = data.get('current_page')
        book_instance.save()

        return JsonResponse({'status': 'success'})

catalog/templates/books/book_detail.html
{% extends "base_generic.html" %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/book_author_detail.css' %}">
{% endblock %}

{% block content %}
<main class="row">
  <section class="col">
    <div id="detail-card">
      <h1>{{ book.title }}</strong></h1>
      <h5><strong>Auteur :</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></h5>
      <h5><strong>Langage :</strong> {{ book.language }}</h5>
      <h5><strong>Genre :</strong> {{ book.genre.all|join:", " }}</h5>
      <h5><strong>ISBN :</strong> {{ book.isbn }}</h5>
      <h5><strong>Description :</strong><br>{{ book.summary }}</h5>
    </div>
  </section>
<section class="col">
  <h3>Exemplaires :</h3>
  {% if user.is_authenticated %}
  {% if book.bookinstance_set.all %}
  <div class="book-copies">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Statut</th>
          <th scope="col" class="col-optional">Date d'impression</th>
          <th scope="col">Emprunter/Retourner</th>
        </tr>
      </thead>
      <tbody>
        <!-- "_set"(.all) est une fonction de Django permettant de retrouver la partie "Many" d'une relation 
          (étant donné que la relation OneToMany n'a été déclarée que du côté One donc du côté du model "book"). 
          Ainsi, je vais pouvour retrouver tous les enregistrements "bookinstance" associés à mon objet "book". 
        -->
        {% for copy in book.bookinstance_set.all %}
        <tr>
          <td>
            <div class="book-status {% if copy.status == 'a' %}bg-success{% elif copy.status == 'm' %}bg-danger{% else %}bg-warning{% endif %}">
              {{ copy.get_status_display }}
            </div>
          </td>
          <td class="col-optional">{{ copy.imprint }}</td>
          <td>
              {% if copy.status == 'a' %}
                <form action="{{ request.path }}" method="post">
                  {% csrf_token %}
                  <input class="button" type="submit" value="Emprunter" />
                  <input type="hidden" name="borrow_book" value="/" />
                  <input type="hidden" name="copy_id" value="{{ copy.id }}" />
                  <input type="hidden" name="user_id" value="{{ user.id }}" />
                </form>
              {% elif copy.status == 'o' %}
                {% if user == copy.borrower %}
                  <a class="button" href="{% url 'book-renew' copy.pk %}?next={% url 'book-detail' book.id %}">Prolonger</a>
                  <a class="button" href="{% url 'book-return' copy.pk %}?next={% url 'book-detail' book.id %}">Retourner</a>
                {% else %}
                  <strong>Document emprunté par :</strong> {{ copy.borrower }}<br>
                  <strong>Date de retour :</strong> {{ copy.due_back|date:"d/m/Y" }}
                {% endif %}
              {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
  <div class="login">
    <p>Aucun exemplaire disponible.</p>
  </div>
{% endif %}
{% else %}
  <div class="login">
    <p>Veuillez vous connecter pour accéder au statut du document.</p>
    <a class="button" href="{% url 'login' %}?next={% url 'book-detail' book.id %}">Se connecter</a>
  </div>
</section>
{% endif %}
</main>
{% endblock %}

catalog/templates/books/book_renew.html
{% extends "base_generic.html" %}

{% block css %}
<style>
  h1 + p {
    margin-top: 5%;
  }

  form input[type="submit"] {
    margin-top: 1.5%;
  }

</style>
{% endblock %}
{% block content %}
<main>
  <h1>Renouveler : {{ book_instance.book.title }}</h1>
  <p>Emprunteur : {{ book_instance.borrower }}</p>
  <p {% if book_instance.is_overdue %} class="text-danger"{% endif %}>Date de retour : {{ book_instance.due_back|date:"d/m/Y" }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_p }}
    </table>
    <input type="submit" class="button" value="Renouveler">
  </form>
</main>
{% endblock %}

catalog/templates/books/books_list.html
{% extends "base_generic.html" %} 

{% block title %}Livres{% endblock %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/books_authors_list.css' %}">
{% endblock %}

{% block content %}
<main>
<h1>Livres</h1>
{% if books_list %}
<div>
  <form>{% csrf_token %}</form>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"><button class="search-filter">Titre</button></th>
        <th scope="col"><button class="search-filter">Auteur</button></th>
        {% if perms.can_change_book and perms.can_delete_book %}
        <th scope="col">Mettre à jour</th>
        <th scope="col">Supprimer</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for book in books_list %}
      <tr>
        <td><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></td>
        <td><a href="{% url 'author-detail' book.author.id %}">{{ book.author }}</a></td>
        {% if perms.can_change_book and perms.can_delete_book %}
        <td><a href="{% url 'book-update' book.pk %}">Mettre à jour</a></td>
        <td><a href="{% url 'book-delete' book.pk %}">Supprimer</a></td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<p>There are no books in the library.</p>
{% endif %}
</main>
{% endblock %}

{% block js %}
  {% load static %}
  <script src="{% static 'js/book_list_filters.js' %}"></script>
{% endblock %}